# Generated by Django 5.2.1 on 2025-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Researchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('IDX', 'Index'), ('STK', 'Stock'), ('CRY', 'Currency Pair'), ('COM', 'Commodity')], default='STK', max_length=3),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
